### ISSUE TITLE
query_prefix in examples

### ISSUE THREAD

**Issue by xiyang-aads-lilly** [Snowflake-Labs/arctic-embed#1]
Thank you for this amazing project.

I have a question about the example in the readme.

In the `Using Sentence Transformers` example, it does not use query_prefix but in the Huggingface example, it recommends to use query prefix.  I would like to confirm if query_prefix is "required" to achieve better performance for QA retrieve tasks.

Thanks!

**Comment by hfawaz** [comment]
yes you need the prefix, tried it

**Comment by xiyang-aads-lilly** [comment]
Thanks!
